// Plemena psů a koček s vlastnostmi, podle kterých se párují vhodná jména.
// `doporucena` jsou ručně vybraná jména na míru plemeni (historie, film,
// mytologie, zima…) — musí existovat v katalogu a odpovídat druhu zvířete.

import type { Plemeno } from './types'

export const PLEMENA_PSU: Plemeno[] = [
  { nazev: 'Labradorský retrívr',       druh: 'pes', velikost: 'velké',   energie: 'živá',     styly: ['hravé', 'sportovní'],      puvod: 'gb', popis: 'Věčné štěně s dobrým srdcem — hodí se přátelská, hravá jména.',
    doporucena: ['Marley', 'Buddy', 'Max', 'Cooper', 'Bella', 'Sadie', 'Mel', 'Ben'] },
  { nazev: 'Zlatý retrívr',             druh: 'pes', velikost: 'velké',   energie: 'vyvážená', styly: ['hravé', 'tradiční'],       puvod: 'gb', popis: 'Rodinný dobrák — sluší mu hřejivá, laskavá jména.',
    doporucena: ['Shadow', 'Buddy', 'Teddy', 'Maggie', 'Daisy', 'Nala', 'Honey'] },
  { nazev: 'Německý ovčák',             druh: 'pes', velikost: 'velké',   energie: 'živá',     styly: ['tradiční', 'královské'],   puvod: 'de', popis: 'Ochránce a pracant — nese důstojná, pevná jména.',
    doporucena: ['Rex', 'Blitz', 'Aron', 'Cézar', 'Sultan', 'Elza', 'Kessy'] },
  { nazev: 'Francouzský buldoček',      druh: 'pes', velikost: 'malé',    energie: 'klidná',   styly: ['hravé', 'elegantní'],      puvod: 'fr', popis: 'Gaučový šarmér — sedí mu vtipná i pařížsky elegantní jména.',
    doporucena: ['Gaston', 'Filou', 'Oscar', 'Coco', 'Fifi', 'Belle', 'Titou'] },
  { nazev: 'Čivava',                    druh: 'pes', velikost: 'malé',    energie: 'živá',     styly: ['hravé', 'moderní'],        puvod: 'es', popis: 'Malé tělo, velké ego — kontrastní a temperamentní jména fungují skvěle.',
    doporucena: ['Chico', 'Chispa', 'Bonita', 'Che', 'Fifi', 'Linda'] },
  { nazev: 'Jezevčík',                  druh: 'pes', velikost: 'malé',    energie: 'vyvážená', styly: ['tradiční', 'hravé'],       puvod: 'de', popis: 'Tvrdohlavý lovec v malém balení — klasická i šibalská jména.',
    doporucena: ['Fritz', 'Punťa', 'Baryk', 'Fafik', 'Heidi', 'Dina'] },
  { nazev: 'Pudl',                      druh: 'pes', velikost: 'střední', energie: 'vyvážená', styly: ['elegantní', 'moderní'],    puvod: 'fr', popis: 'Inteligence a noblesa — elegantní jména jsou sázka na jistotu.',
    doporucena: ['Coco', 'Belle', 'Oscar', 'Perle', 'Mirza', 'Lady'] },
  { nazev: 'Border kolie',              druh: 'pes', velikost: 'střední', energie: 'živá',     styly: ['sportovní', 'přírodní'],   puvod: 'gb', popis: 'Nejchytřejší pes světa — krátká, akční jména na povel.',
    doporucena: ['Lassie', 'Chase', 'Kessy', 'Rayo', 'Ajda', 'Bady'] },
  { nazev: 'Jack Russell teriér',       druh: 'pes', velikost: 'malé',    energie: 'živá',     styly: ['hravé', 'sportovní'],      puvod: 'gb', popis: 'Neřízená střela — jméno musí stíhat jeho tempo.',
    doporucena: ['Milou', 'Rocky', 'Ziggy', 'Buster', 'Chispa', 'Pipoca'] },
  { nazev: 'Yorkšírský teriér',         druh: 'pes', velikost: 'malé',    energie: 'živá',     styly: ['elegantní', 'hravé'],      puvod: 'gb', popis: 'Mašle a kuráž — drobná elegantní jména.',
    doporucena: ['Fifi', 'Bety', 'Missy', 'Pippa', 'Titou', 'Perle'] },
  { nazev: 'Mops',                      druh: 'pes', velikost: 'malé',    energie: 'klidná',   styly: ['hravé'],                   puvod: 'de', popis: 'Chrochtavý pohodář — roztomilá a vtipná jména.',
    doporucena: ['Winston', 'Punťa', 'Momo', 'Mel', 'Heidi'] },
  { nazev: 'Bígl',                      druh: 'pes', velikost: 'střední', energie: 'živá',     styly: ['hravé', 'tradiční'],       puvod: 'gb', popis: 'Nos na stopě, uši ve větru — veselá jména.',
    doporucena: ['Snoopy', 'Baryk', 'Bidu', 'Lucy', 'Bety', 'Alfie'] },
  { nazev: 'Sibiřský husky',            druh: 'pes', velikost: 'velké',   energie: 'živá',     styly: ['přírodní', 'mytologické'], puvod: 'se', popis: 'Vlčí vzhled, toulavé srdce — zimní jména a hrdinové severu mu sluší nejvíc.',
    doporucena: ['Balto', 'Togo', 'Yukon', 'Tundra', 'Aspen', 'Winter', 'Odin', 'Loke', 'Thor', 'Ylva', 'Neve', 'Denali', 'Aurora', 'Chinook'] },
  { nazev: 'Bernský salašnický pes',    druh: 'pes', velikost: 'velké',   energie: 'klidná',   styly: ['tradiční', 'přírodní'],    puvod: 'de', popis: 'Huňatý dobrák z hor — klidná, hřejivá jména.',
    doporucena: ['Bamse', 'Bruno', 'Bear', 'Frieda', 'Bela', 'Gaston'] },
  { nazev: 'Kavalír King Charles španěl', druh: 'pes', velikost: 'malé',  energie: 'klidná',   styly: ['královské', 'elegantní'],  puvod: 'gb', popis: 'Královský mazel — vznešená jména má v rodokmenu.',
    doporucena: ['Lady', 'Winston', 'Belle', 'Millie', 'Oscar', 'Rosie'] },
  { nazev: 'Německá doga',              druh: 'pes', velikost: 'velké',   energie: 'klidná',   styly: ['královské', 'tradiční'],   puvod: 'de', popis: 'Něžný obr — velkolepé jméno unese levou zadní.',
    doporucena: ['Scooby', 'Cézar', 'Rex', 'Duke', 'Elza', 'Toro'] },
  { nazev: 'Shiba inu',                 druh: 'pes', velikost: 'střední', energie: 'vyvážená', styly: ['přírodní', 'tradiční'],    puvod: 'jp', popis: 'Liščí samuraj s vlastní hlavou — japonská jména mu sluší nejvíc.',
    doporucena: ['Hachi', 'Taro', 'Kotaro', 'Shiro', 'Yuki', 'Momo', 'Koharu', 'Kuro'] },
  { nazev: 'Australský ovčák',          druh: 'pes', velikost: 'střední', energie: 'živá',     styly: ['sportovní', 'přírodní'],   puvod: 'au', popis: 'Pastevec s modrýma očima — akční jména z divočiny.',
    doporucena: ['Bluey', 'Chase', 'Rusty', 'Kirra', 'Bindi', 'Rayo'] },
]

export const PLEMENA_KOCEK: Plemeno[] = [
  { nazev: 'Britská krátkosrstá', druh: 'kocka', energie: 'klidná',   styly: ['tradiční', 'královské'],   puvod: 'gb', popis: 'Plyšový gentleman — důstojná britská jména.',
    doporucena: ['Monty', 'Oscar', 'Jasper', 'Tilly', 'Molly', 'Misty'] },
  { nazev: 'Mainská mývalí',      druh: 'kocka', energie: 'vyvážená', styly: ['přírodní', 'mytologické'], puvod: 'us', popis: 'Něžný obr — velká jména pro velkou kočku.',
    doporucena: ['Grizzly', 'Frost', 'Nanuk', 'Loki', 'Simba', 'Sable'] },
  { nazev: 'Siamská',             druh: 'kocka', energie: 'živá',     styly: ['elegantní', 'moderní'],    puvod: 'jp', popis: 'Upovídaná elegance — melodická exotická jména.',
    doporucena: ['Tama', 'Hime', 'Mei', 'Chai', 'Kali', 'Yuzu'] },
  { nazev: 'Ragdoll',             druh: 'kocka', energie: 'klidná',   styly: ['elegantní', 'hravé'],      puvod: 'us', popis: 'Hadrová panenka na klíně — něžná mazlivá jména.',
    doporucena: ['Pelusa', 'Nube', 'Mimosa', 'Perlita', 'Micia', 'Dolce'] },
  { nazev: 'Perská',              druh: 'kocka', energie: 'klidná',   styly: ['královské', 'elegantní'],  puvod: 'eg', popis: 'Aristokratka s hřívou — vznešená orientální jména.',
    doporucena: ['Bastet', 'Hime', 'Afrodita', 'Olympia', 'Nubia', 'Perlička'] },
  { nazev: 'Bengálská',           druh: 'kocka', energie: 'živá',     styly: ['přírodní', 'sportovní'],   puvod: 'us', popis: 'Leopard v obýváku — divoká přírodní jména.',
    doporucena: ['Tora', 'Tigre', 'Sahara', 'Kali', 'Rangi', 'Pepper'] },
  { nazev: 'Norská lesní',        druh: 'kocka', energie: 'vyvážená', styly: ['mytologické', 'přírodní'], puvod: 'se', popis: 'Vikingská kočka — severská mytologie jak dělaná.',
    doporucena: ['Loki', 'Findus', 'Sixten', 'Tindra', 'Vilda', 'Selma'] },
  { nazev: 'Ruská modrá',         druh: 'kocka', energie: 'klidná',   styly: ['elegantní'],               puvod: 'se', popis: 'Stříbrná tichost — jemná elegantní jména.',
    doporucena: ['Zora', 'Signe', 'Ivory', 'Bianca', 'Misty', 'Platon'] },
  { nazev: 'Sphynx',              druh: 'kocka', energie: 'živá',     styly: ['mytologické', 'moderní'],  puvod: 'eg', popis: 'Bezsrstá záhada — egyptská jména jsou povinnost.',
    doporucena: ['Ra', 'Osiris', 'Horus', 'Bastet', 'Kleio', 'Ikaros'] },
  { nazev: 'Evropská krátkosrstá', druh: 'kocka', energie: 'vyvážená', styly: ['tradiční', 'hravé'],      puvod: 'cz', popis: 'Domácí poklad — klasická jména od Mikeše po Micku.',
    doporucena: ['Mikeš', 'Micka', 'Mourek', 'Macek', 'Mína', 'Líza'] },
]

export const VSECHNA_PLEMENA = [...PLEMENA_PSU, ...PLEMENA_KOCEK]
